language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
notifications:
  email: false
sudo: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'