language: julia
os:
  - linux
julia:
  - 1.0
  - 1.3
notifications:
  email: false
sudo: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
after_success:
  - julia -e 'cd(Pkg.dir("sparseQFCA.jl")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(Codecov.process_folder())'
